<?php

namespace Database\Seeders;

use App\Models\Flashcard;
use App\Models\Language;
use Illuminate\Database\Seeder;

class FlashcardSeeder extends Seeder
{
    public function run(): void
    {
        $cardsByLanguage = [
            'Polish' => [
                ['Hello', 'Cześć'],
                ['Thank you', 'Dziękuję'],
                ['Please', 'Proszę'],
                ['Yes', 'Tak'],
                ['No', 'Nie'],
                ['Good morning', 'Dzień dobry'],
                ['Good night', 'Dobranoc'],
                ['Sorry', 'Przepraszam'],
                ['Excuse me', 'Przepraszam'],
                ['Goodbye', 'Do widzenia'],
                ['Friend', 'Przyjaciel'],
                ['Water', 'Woda'],
                ['Food', 'Jedzenie'],
                ['House', 'Dom'],
                ['Car', 'Samochód'],
                ['Work', 'Praca'],
                ['School', 'Szkoła'],
                ['Book', 'Książka'],
                ['City', 'Miasto'],
                ['Street', 'Ulica'],
                ['Left', 'Lewo'],
                ['Right', 'Prawo'],
                ['Today', 'Dzisiaj'],
                ['Tomorrow', 'Jutro'],
                ['Yesterday', 'Wczoraj'],
                ['Morning', 'Rano'],
                ['Evening', 'Wieczór'],
                ['Night', 'Noc'],
                ['Day', 'Dzień'],
                ['Week', 'Tydzień'],
                ['Month', 'Miesiąc'],
                ['Year', 'Rok'],
                ['Family', 'Rodzina'],
                ['Mother', 'Matka'],
                ['Father', 'Ojciec'],
                ['Brother', 'Brat'],
                ['Sister', 'Siostra'],
                ['Child', 'Dziecko'],
                ['Money', 'Pieniądze'],
                ['Price', 'Cena'],
                ['Ticket', 'Bilet'],
                ['Train', 'Pociąg'],
                ['Bus', 'Autobus'],
                ['Airport', 'Lotnisko'],
                ['Help', 'Pomoc'],
                ['Hospital', 'Szpital'],
                ['Pharmacy', 'Apteka'],
                ['Bathroom', 'Łazienka'],
                ['Coffee', 'Kawa'],
                ['Tea', 'Herbata'],
                ['Beer', 'Piwo'],
            ],
            'Danish' => [
                ['Hello', 'Hej'],
                ['Thank you', 'Tak'],
                ['Please', 'Vær så venlig'],
                ['Yes', 'Ja'],
                ['No', 'Nej'],
                ['Good morning', 'Godmorgen'],
                ['Good night', 'Godnat'],
                ['Sorry', 'Undskyld'],
                ['Excuse me', 'Undskyld mig'],
                ['Goodbye', 'Farvel'],
                ['Friend', 'Ven'],
                ['Water', 'Vand'],
                ['Food', 'Mad'],
                ['House', 'Hus'],
                ['Car', 'Bil'],
                ['Work', 'Arbejde'],
                ['School', 'Skole'],
                ['Book', 'Bog'],
                ['City', 'By'],
                ['Street', 'Gade'],
                ['Left', 'Venstre'],
                ['Right', 'Højre'],
                ['Today', 'I dag'],
                ['Tomorrow', 'I morgen'],
                ['Yesterday', 'I går'],
                ['Morning', 'Morgen'],
                ['Evening', 'Aften'],
                ['Night', 'Nat'],
                ['Day', 'Dag'],
                ['Week', 'Uge'],
                ['Month', 'Måned'],
                ['Year', 'År'],
                ['Family', 'Familie'],
                ['Mother', 'Mor'],
                ['Father', 'Far'],
                ['Brother', 'Bror'],
                ['Sister', 'Søster'],
                ['Child', 'Barn'],
                ['Money', 'Penge'],
                ['Price', 'Pris'],
                ['Ticket', 'Billet'],
                ['Train', 'Tog'],
                ['Bus', 'Bus'],
                ['Airport', 'Lufthavn'],
                ['Help', 'Hjælp'],
                ['Hospital', 'Hospital'],
                ['Pharmacy', 'Apotek'],
                ['Bathroom', 'Badeværelse'],
                ['Coffee', 'Kaffe'],
                ['Tea', 'Te'],
                ['Beer', 'Øl'],
            ],
            'German' => [
                ['Hello', 'Hallo'],
                ['Thank you', 'Danke'],
                ['Please', 'Bitte'],
                ['Yes', 'Ja'],
                ['No', 'Nein'],
                ['Good morning', 'Guten Morgen'],
                ['Good night', 'Gute Nacht'],
                ['Sorry', 'Entschuldigung'],
                ['Excuse me', 'Entschuldigen Sie'],
                ['Goodbye', 'Auf Wiedersehen'],
                ['Friend', 'Freund'],
                ['Water', 'Wasser'],
                ['Food', 'Essen'],
                ['House', 'Haus'],
                ['Car', 'Auto'],
                ['Work', 'Arbeit'],
                ['School', 'Schule'],
                ['Book', 'Buch'],
                ['City', 'Stadt'],
                ['Street', 'Straße'],
                ['Left', 'Links'],
                ['Right', 'Rechts'],
                ['Today', 'Heute'],
                ['Tomorrow', 'Morgen'],
                ['Yesterday', 'Gestern'],
                ['Morning', 'Vormittag'],
                ['Evening', 'Abend'],
                ['Night', 'Nacht'],
                ['Day', 'Tag'],
                ['Week', 'Woche'],
                ['Month', 'Monat'],
                ['Year', 'Jahr'],
                ['Family', 'Familie'],
                ['Mother', 'Mutter'],
                ['Father', 'Vater'],
                ['Brother', 'Bruder'],
                ['Sister', 'Schwester'],
                ['Child', 'Kind'],
                ['Money', 'Geld'],
                ['Price', 'Preis'],
                ['Ticket', 'Fahrkarte'],
                ['Train', 'Zug'],
                ['Bus', 'Bus'],
                ['Airport', 'Flughafen'],
                ['Help', 'Hilfe'],
                ['Hospital', 'Krankenhaus'],
                ['Pharmacy', 'Apotheke'],
                ['Bathroom', 'Badezimmer'],
                ['Coffee', 'Kaffee'],
                ['Tea', 'Tee'],
                ['Beer', 'Bier'],
            ],
        ];

        foreach ($cardsByLanguage as $languageName => $cards) {
            $language = Language::where('name', $languageName)->first();

            if (! $language) {
                continue;
            }

            foreach ($cards as [$term, $translation]) {
                Flashcard::updateOrCreate(
                    ['language_id' => $language->id, 'term' => $term],
                    ['language_id' => $language->id, 'translation' => $translation]
                );
            }
        }
    }
}
